name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.7

      - name: Build & Run Java tests
        run: ./gradlew build assembleAndroidTest --info --stacktrace

      - name: Junit Report to Annotations
        uses: ashley-taylor/junit-report-annotations-action@1.2
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "**/TEST-*.xml"
          testSrcPath: "mediation/src/test/java"

  deploy-development-artifacts:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.7

      - name: Deploy artifacts
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
        run: ./gradlew bintrayUpload